import image from './image.png'

export const coreItem = [
    {
        images: [image],
        colors: ['1b1b1b'],
        name: 'GeForce RTX',
        series: '3060 Ti',
        price: '70 000 руб.',
        modelCode: '36ISM6MD2KCK',
        productCode: '36ISM6MD2KCK',
        fanStop: 'Да',
        fanType: 'WINGS',
        fanSize: '102 - 102',
        backplate: 'Металл',
        // lightZone: light1,
        clockPurityClick: '1 680',
        clockPurity: '1 665',
        clickPurityBase: '1 410',
        nvidiaCuda: '4 864',
        baseMemoryConfiguration: '8ГБ GDDR6X',
        throughput: '608',
        screenResolution: '7680x4320',
        displayConnectors: 'HDMI, 3 разъема DisplayPort',
        displaySupport: 'до 4',
        videoCardSize: '238 x 128 x 54',
        slots: '2.8',
        supply: '600',
        supplyConnectors: 'Один 8-контактный кабель PCIe.',
        set: 'QR код с инструкцией',
    },
    {
        images: [image],
        colors: ['1b1b1b'],
        name: 'GeForce RTX',
        series: '3060 TI',
        price: '70 000 руб.',
        modelCode: '36ISL6MD1VQK',
        productCode: '36ISL6MD1VQK',
        fanStop: 'Да',
        fanType: 'WINGS',
        fanSize: '90 - 90',
        backplate: 'Металл',
        // lightZone: light2,
        clockPurityClick: '1 680',
        clockPurity: '1 665',
        clickPurityBase: '1 410',
        nvidiaCuda: '4 864',
        baseMemoryConfiguration: '8ГБ GDDR6',
        throughput: '448',
        screenResolution: '7680x4320',
        displayConnectors: 'HDMI, 3 разъема DisplayPort',
        displaySupport: 'до 4',
        videoCardSize: '242.5 x 118.65 x 38.6',
        // videoCardSizeImage: size,
        slots: '2',
        supply: '600',
        supplyConnectors: 'Один 8-контактный кабель PCIe.',
        set: 'QR код с инструкцией',
    },
    {
        images: [image],
        colors: ['1b1b1b'],
        name: 'GeForce RTX',
        series: '3060',
        price: '70 000 руб.',
        modelCode: '36NOL7MD1VOK',
        productCode: '36NOL7MD1VOK',
        fanStop: 'Да',
        fanType: 'WINGS',
        fanSize: '90 - 90',
        backplate: 'Металл',
        // lightZone: light3,
        clockPurityClick: '1 792',
        clockPurity: '1 777',
        clickPurityBase: '1 320',
        nvidiaCuda: '3 584',
        baseMemoryConfiguration: '12ГБ GDDR6',
        throughput: '360',
        screenResolution: '7680x4320',
        displayConnectors: 'HDMI, 3 разъема DisplayPort',
        displaySupport: 'до 4',
        videoCardSize: '245 x 112 x 41.5',
        // videoCardSizeImage: size,
        slots: '2',
        supply: '550',
        supplyConnectors: 'Один 8-контактный кабель PCIe.',
        set: 'QR код с инструкцией',
    },
    {
        images: [image],
        colors: ['1b1b1b'],
        name: 'GeForce RTX',
        series: '3060',
        price: '70 000 руб.',
        modelCode: '36NSL8MD6OCK',
        productCode: '36NSL8MD6OCK',
        fanStop: 'Да',
        fanType: 'WINGS',
        fanSize: '90 - 90',
        backplate: 'Металл',
        // lightZone: light3,
        clockPurityClick: '1 792',
        clockPurity: '1 777',
        clickPurityBase: '1 320',
        nvidiaCuda: '3 584',
        baseMemoryConfiguration: '8ГБ GDDR6',
        throughput: '360',
        screenResolution: '7680x4320',
        displayConnectors: 'HDMI, 3 разъема DisplayPort',
        displaySupport: 'до 4',
        videoCardSize: '245 x 112 x 41.5',
        // videoCardSizeImage: size,
        slots: '2',
        supply: '550',
        supplyConnectors: 'Один 8-контактный кабель PCIe.',
        set: 'QR код с инструкцией',
    },
]
