import image from './image.png'
import size1 from './size1.png'
import size from './size.png'

export const coreItem = [
    {
        images: [image],
        colors: ['1b1b1b'],
        name: 'GeForce RTX',
        series: '4070 SUPER',
        price: '70 000 руб.',
        modelCode: 'KD71437',
        productCode: '47SOM7MD9PSK\n',
        fanStop: 'Да',
        fanType: 'WINGS 2.0',
        fanSize: '92 - 92',
        backplate: 'Металл',
        lightType: 'LED',
        clockPurityClick: '2 490',
        clockPurity: '2 475',
        clickPurityBase: '1 980',
        nvidiaCuda: '7 168',
        baseMemoryConfiguration: '12ГБ GDDR6X',
        throughput: '504',
        screenResolution: '4K при 240 Гц или 8K при 60 Гц с поддержкой DSC, HDR',
        displayConnectors: 'HDMI, 3 разъема DisplayPort',
        displaySupport: 'до 4',
        videoCardSize: '238 x 115 x 45',
        videoCardSizeImage: size1,
        slots: '2.2',
        supply: '600',
        supplyConnectors: '12VHPWR',
        set: 'QR код с инструкцией'
    },
    {
        images: [image],
        colors: ['1b1b1b'],
        name: 'GeForce RTX',
        series: '4070',
        price: '70 000 руб.',
        modelCode: 'KD71403',
        productCode: '47NOM7MD8DDK',
        fanStop: 'Да',
        fanType: 'WINGS 2.0',
        fanSize: '92 - 92',
        backplate: 'Металл',
        lightType: 'LED',
        clockPurityClick: '2 490',
        clockPurity: '2 475',
        clickPurityBase: '1 920',
        nvidiaCuda: '5 888',
        baseMemoryConfiguration: '12ГБ GDDR6X',
        throughput: '504',
        screenResolution: '4K при 240 Гц или 8K при 60 Гц с поддержкой DSC, HDR',
        displayConnectors: 'HDMI, 3 разъема DisplayPort',
        displaySupport: 'до 4',
        videoCardSize: '238 x 115 x 45',
        videoCardSizeImage: size1,
        slots: '2',
        supply: '650',
        supplyConnectors: 'Один 8-контактный кабель PCIe.',
        set: 'QR код с инструкцией'
    },
    {
        images: [image],
        colors: ['1b1b1b'],
        name: 'GeForce RTX',
        series: '4060 TI',
        price: '70 000 руб.',
        modelCode: 'KD60903',
        productCode: '46ISL8MD8COK',
        fanStop: 'Да',
        fanType: 'WINGS 2.0',
        fanSize: '92 - 92',
        backplate: 'Металл',
        lightType: 'LED',
        clockPurityClick: '2 565',
        clockPurity: '2 550',
        clickPurityBase: '2 310',
        nvidiaCuda: '4 352',
        baseMemoryConfiguration: '8ГБ GDDR6X',
        throughput: '288',
        screenResolution: '4K при 240 Гц или 8K при 60 Гц с поддержкой DSC, HDR',
        displayConnectors: 'HDMI, 3 разъема DisplayPort',
        displaySupport: 'до 4',
        videoCardSize: '237 x 118 x 41',
        videoCardSizeImage: size,
        slots: '2',
        supply: '550',
        supplyConnectors: 'Один 8-контактный кабель PCIe.',
        set: 'QR код с инструкцией'
    },
    {
        images: [image],
        colors: ['1b1b1b'],
        name: 'GeForce RTX',
        series: '4060',
        price: '70 000 руб.',
        modelCode: 'KD61403',
        productCode: '46NSL8MD8LOK',
        fanStop: 'Да',
        fanType: 'WINGS 2.0',
        fanSize: '92 - 92',
        backplate: 'Металл',
        lightType: 'LED',
        clockPurityClick: '2 490',
        clockPurity: '2 475',
        clickPurityBase: '1 830',
        nvidiaCuda: '3 072',
        baseMemoryConfiguration: '12ГБ GDDR6X',
        throughput: '272',
        screenResolution: '4K при 240 Гц или 8K при 60 Гц с поддержкой DSC, HDR',
        displayConnectors: 'HDMI, 3 разъема DisplayPort',
        displaySupport: 'до 4',
        videoCardSize: '237 x 118 x 41',
        videoCardSizeImage: size,
        slots: '2',
        supply: '650',
        supplyConnectors: 'Один 8-контактный кабель PCIe.',
        set: 'QR код с инструкцией'
    },
]
