import image1 from "./image1.png"
import image2 from './image2.png'
import image2White from './image2White.png'
import image3 from './image3.png'
import image3White from './image3White.png'
import image4 from './image4.png'
import image4White from './image4White.png'

export const xItem = [
    {
        images: [image4, image4White],
        colors: ['1b1b1b', 'e1e1e1'],
        name: 'GeForce RTX',
        series: '3050',
        price: '70 000 руб.',
        modelCode: '35NSL8MD6YEK / 35NSL8MD5WEK',
        productCode: '35NSL8MD6YEK / 35NSL8MD5WEK',
        fanStop: 'Да',
        fanType: 'WINGS',
        fanSize: '92 - 92',
        backplate: 'Металл',
        lightType: 'LED',
        // lightZone: light3,
        clockPurityClick: '1 837',
        clockPurity: '1 822',
        clickPurityBase: '1 550',
        nvidiaCuda: '2 560',
        baseMemoryConfiguration: '8ГБ GDDR6',
        throughput: '224',
        screenResolution: '7680x4320',
        displayConnectors: 'HDMI, 3 разъема DisplayPort',
        displaySupport: 'до 4',
        videoCardSize: '209 x 118 x 41,5',
        // videoCardSizeImage: size,
        slots: '2',
        supply: '550',
        supplyConnectors: 'Один 8-контактный кабель PCIe.',
        set: 'QR код с инструкцией',
    },
    {
        images: [image1],
        colors: ['1b1b1b'],
        name: 'GeForce RTX',
        series: '3050',
        price: '70 000 руб.',
        modelCode: '35NRLDMD9OEK',
        productCode: '35NRLDMD9OEK',
        fanStop: 'Да',
        fanType: 'WINGS',
        fanSize: '92 - 92',
        backplate: 'Да',
        lightType: '-',
        // lightZone: light3,
        clockPurityClick: '1 485',
        clockPurity: '1 470',
        clickPurityBase: '1 042',
        nvidiaCuda: '2 304',
        baseMemoryConfiguration: '6ГБ GDDR6',
        throughput: '168',
        screenResolution: '7680x4320',
        displayConnectors: 'HDMI, 3 разъема DisplayPort',
        displaySupport: 'до 4',
        videoCardSize: '209 x 118 x 41,5',
        // videoCardSizeImage: size,
        slots: '2',
        supply: '300',
        supplyConnectors: 'Один 8-контактный кабель PCIe.',
        set: 'QR код с инструкцией',
    },
]
