import image from "./image.png"

export const vivance32q =
    {
        image: image,
        name: 'Vivance 32Q',
        price: '70 000 руб.',
        modelCode: 'MKVIBF32NB50',
        productCode: 'MKVIBF32NB50',
        productEan: '-',
        diagonal: '32"',
        maxpermission: '2560 x 1440',
        sides: '16:9',
        light: 'LED',
        manufacturing: 'IPS',
        frequency: '165 Гц',
        coating: 'Матовое',
        corner: '178°/178°',
        mprt: '1 мс',
        gtg: '5 мс',
        bright: '300 Кд/м²',
        contrast: '1000:1',
        hdrsupport: 'Да',
        colordeep: '10 bit',
        srgb: '100%',
        argb: '90%',
        care: 'Flicker Free, Low Blue Light',
        update: 'NVIDIA G-SYNC Compatible,  AMD FreeSync Compatible',
        bracing: 'VESA',
        bracingsize: '100 x 100',
        size: '724,3 x 424,2 x 46,3 мм',
        bigsize: '724,3 x 497,4 x 182,2 мм',
        weight: '5,5',
        po: 'Нет',
        setting: 'OSD - On Screen Dysplay. Настройка параметров работы монитора осуществляется с помощью специального меню, выводимого поверх изображения экрана. Выбор и редактирование профилей, настройки HDR, яркости и контрастности. Полная поддержка русского языка.',
        videoconnect: 'DisplayPort x2, HDMI x2',
        audioconnect: 'Да',
        set: 'Блок питания, документация, кабель DisplayPort, кабель питания.'
    }

